# Generated by Django 2.2.12 on 2022-03-28 10:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
