# Generated by Django 2.2.12 on 2022-03-28 13:34

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220328_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='hash',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix=''),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='hash',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix=''),
        ),
    ]
